version: '3.8'

services:
  backend:
    container_name: oinkbrew_api
    build: backend/.
    command: npm run start:dev
    depends_on:
      - postgresql
    ports:
      - "3000:3000"
    environment:
      JWT_OTP_TOKEN_SECRET: "169ed2a7-cfbb-4d8a-ba41-abd75ac40f74"
      JWT_OTP_TOKEN_EXPIRATION_TIME: "15"
      JWT_ACCESS_TOKEN_SECRET: "7a81ac07-30c1-40bd-82af-a60536038464"
      JWT_ACCESS_TOKEN_EXPIRATION_TIME: "15"
      JWT_REFRESH_TOKEN_SECRET: "bfc23553-ab7a-4d01-b7d7-9602a00db09b"
      JWT_REFRESH_TOKEN_EXPIRATION_TIME: "7"
      DATABASE_URL: "postgresql://postgres:123@localhost:5432/oinkbrew?schema=public"
    volumes:
      - ./backend/.:/opt/app
      - /opt/app/node_modules

  postgresql:
    image: postgres:13
    container_name: oinkbrew_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: oinkbrew
