version: '3.8'

services:
  database:
    image: postgres:15.1-alpine
    container_name: oinkbrew-e2e-db
    restart: 'unless-stopped'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: oinkbrew
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - database:/var/lib/postgresql/data # This is where the database data is stored - a docker volume
      - ./backup:/backup

  cache:
    image: redis:7.0.5-alpine
    container_name: oinkbrew-e2e-cache
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

volumes:
  database:
    name: oinkbrew-e2e-db
  cache:
    name: oinkbrew-e2e-cache
    driver: local
